### ISSUE TITLE
Passing token to own API

### ISSUE THREAD

**Issue by ghost** [OfficeDev/O365-Angular-Unified-API-Connect#7]
Hi,

Thanks for the sample, it's a really helpful piece of code. 

As far as I understand, the ADAL angular library intercepts all requests to graph.microsoft.com and adds the appropriate tokens to those requests. Is there any way to get the actual tokens that the ADAL library fetches? I'd like to have my API perform the requests on behalf of the user (something like: client -> my api -> graph.microsoft.com) so that I can filter / perform some operations on the data coming back from the graph api, and then return that 'updated' data to the client.

I guess I could just provide all the required fields to my api, and have my api request tokens and then use those for graph.microsoft.com, but just wondering if there's a better way to do it.

Thanks!

p.s. This is not really an issue, more of a stackoverflow question, but I thought my chances of getting an answer were a bit higher here :)

**Comment by ricalo** [comment]
Hi @rogerthealien,

I'm getting back from a long weekend and just saw your question. If I understand correctly, you have a server-side API that should be getting the tokens instead of the client-side angular app.

In that case, you're better off looking at other samples that we have developed for server-side platforms. For example, we have a similar sample for [node.js](../../nodejs-connect-rest-sample). What language/platform are you using to develop your API?
